### ISSUE TITLE
Token para crear usuario.

### ISSUE THREAD

**Issue by Diego-bih** [CIFP-Pau-Casesnoves-DAW/etv-public-equipo-sol#1]
En el endpoint para crear el usuario, nos pide especificar un token que no tenemos ya que tendría que generarse al crear el usuario.

![image](https://user-images.githubusercontent.com/77398946/217612695-f20b4b3f-4aae-4e20-8069-f4c48aa9eb28.png)
![image](https://user-images.githubusercontent.com/77398946/217613312-0302f23c-cd88-4245-8b93-403592f12a4d.png)

**Comment by JaumeFP** [comment]
Buenas tardes Diego,

Obviamente para obtener el token necesitareis un usuario, ya que la API no esta abierta a todo el mundo., solo a la gente a la cual nosotros queremos dar acceso.

Como indicamos en la descripción principal del swagger, para obtener un usuario, debéis contactar con nosotros a través de el mail que pusimos en la descripción o del link que esta justo debajo de esta misma descripción:
![image](https://user-images.githubusercontent.com/114694207/217624971-6abd4b91-bba5-46df-a7f7-136afbdf9e98.png)

Como os podéis imaginar, no dejaremos los métodos de modificación de la API abiertos para que todo el mundo pueda hacer y deshacer en nuestra base de datos, me parece bastante obvio.

Dicho esto, y ya que has abierto una issue aquí, si queréis un usuario pasadme los datos de este por aquí y yo mismo lo añadiré. Después, con ese usuario, ya os podréis logear a través de login y obtener así un token para poder usar la API al completo.

Los campos que necesito para crear el usuario serian nombre, apellidos, contraseña, correo electrónico, DNI y teléfono.

Para poneros en contacto con nosotros podéis seguir usando las issues, aunque si algo os apremia mas lo suyo seria que me enviaseis un correo directamente, ya que así lo veré antes.

No dudéis en proponernos mejoras o en consultarnos sobre cualquier duda que os pueda surgir.
 
Saludos.

**Comment by Diego-bih** [comment]
Buenas tardes Jaume,

Te adjunto la información de usuario por cada pertinente del grupo:

Primer Usuario:

- Diego
- Ramirez
- 290101Ab
- [diegoalonsoramirez@paucasesnovescifp.cat](mailto:diegoalonsoramirez@paucasesnovescifp.cat)
- 49866023E
- 605469639

Segundo Usuario:

- Lluis
- Noguera
- 0115
- [lluisnoguera@paucasesnovescifp.cat](mailto:lluisnoguera@paucasesnovescifp.cat)
- 78222232Z
- 659910459

Tercer Usuario:

- Ivan
- Zaychev
- 123qsx
- [ivantodorovzaychev@paucasesnovescifp.cat](mailto:ivantodorovzaychev@paucasesnovescifp.cat)
- 49866022Z
- 659910458

Nuestra principal preocupación se basaba en la creación de usuarios en nuestra aplicación, es decir, el apartado de registro. No nos sería posible crear dicho apartado ya que necesitaríamos el token. Dicho esto, aún no hemos recibido la documentación de nuestro projecto asi que el problema se convertiría en una mera especulación de nuestra posible aplicación.

Saludos.

**Comment by JaumeFP** [comment]
Buenas noches Diego,

Los usuarios ya han sido creados.

Si, hable con mi profesor y he procedido a abrir la url de creación de usuario, por tanto ahora cualquier usuario se podrá registrar. 

Debido a ese cambio he tenido que implementar comprobaciones por rol en diferentes métodos, pero eso ya es otro tema.

Saludos.
